<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Radhekrishna-NUC" failures="1" tests="3" name="testngCheck.TestNG_ReportersAndLogs" time="0.009" errors="0" timestamp="2024-03-07T20:38:55 IST" skipped="1">
  <testcase classname="testngCheck.TestNG_ReportersAndLogs" name="testMethod2" time="0.007">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at testngCheck.TestNG_ReportersAndLogs.testMethod2(TestNG_ReportersAndLogs.java:42)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
    </failure>
    <system-out>
      <![CDATA[TestNG_ReportersAndLogs -> testMethod2]]>
    </system-out>
  </testcase> <!-- testMethod2 -->
  <testcase classname="testngCheck.TestNG_ReportersAndLogs" name="testMethod3" time="0.002">
    <skipped/>
  </testcase> <!-- testMethod3 -->
  <testcase classname="testngCheck.TestNG_ReportersAndLogs" name="testMethod1" time="0.000">
    <system-out>
      <![CDATA[TestNG_ReportersAndLogs -> testMethod1]]>
    </system-out>
  </testcase> <!-- testMethod1 -->
  <system-out>
    <![CDATA[TestNG_ReportersAndLogs -> This runs once before class
TestNG_ReportersAndLogs -> This runs once before every Method
TestNG_ReportersAndLogs -> testMethod2
TestNG_ReportersAndLogs -> This runs once after every Method
TestNG_ReportersAndLogs -> This runs once before every Method
TestNG_ReportersAndLogs -> testMethod1
TestNG_ReportersAndLogs -> This runs once after every Method
TestNG_ReportersAndLogs -> This runs once after class]]>
  </system-out>
</testsuite> <!-- testngCheck.TestNG_ReportersAndLogs -->
